
CREATE TABLE Player(
	PlayerID SERIAL NOT NULL CONSTRAINT PK_PlayerID PRIMARY KEY,
	Login  VARCHAR(100) UNIQUE NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	RegisterData TIMESTAMP NOT NULL,
	LastLoginData TIMESTAMP NOT NULL
);